### PR TITLE
mergedFooterMain

### PR DESCRIPTION
**Pull request by Aisha-Umar**
I lost some work in css when i did git pull but then merged the footer branch with the main and pushed again

### CODE REVIEW

**Comment by samanthatarrice** [comment]
Did you do the git pull on the footer branch? (``git pull origin main``)? If you lost some CSS, there should have been a merge conflict before that.

**Review by samanthatarrice — CHANGES_REQUESTED** [review]
Checked out your branch and I'm seeing this. Not sure if you see the same thing locally:
image

**Comment by Aisha-Umar** [comment]
> Checked out your branch and I'm seeing this. Not sure if you see the same thing locally: image

fullsite

**Comment by Aisha-Umar** [comment]
> > Checked out your branch and I'm seeing this. Not sure if you see the same thing locally: image
> 
> fullsite

this is what I have currently on my screen

**Comment by samanthatarrice** [comment]
Looks like you are working on a bigger screen. Can you resize? I'm guessing it happens on smaller screen sizes. 

Also, we will need to move the links to the left of the brand name. The right will have the chat link when a user logs in.

**Comment by Aisha-Umar** [comment]
> Looks like you are working on a bigger screen. Can you resize? I'm guessing it happens on smaller screen sizes.
> 
> Also, we will need to move the links to the left of the brand name. The right will have the chat link when a user logs in.

Yes i was worried about that! What size do you think i should be working for then? 
Did you mean like you have it in the design for the logged in page in the navbar? That still has the links to the right?

**Pull request closed without merging**
